### ISSUE TITLE
Production deploys are prevented with LaravelViteHelper

### ISSUE THREAD

**Issue by kirkbushell** [motomedialab/laravel-vite-helper#19] opened 2024-08-02 11:51 UTC
Seems I have to build my assets locally and push to production when using LaravelViteHelper, as when installing on production, the helper is looking for the manifest - though not sure where or why this is happening after a composer install..

Any ideas?

**Comment by chrispage1** [comment] 2024-08-05 18:38
Hi @kirkbushell

Where abouts are you using the `vite` helper function, have you got a code sample?

Thanks,
Chris.

**Comment by chrispage1** [comment] 2024-08-14 10:19
Hey @kirkbushell - I'm going to close this one. But when using Vite outside of hot mode, if you are loading assets inside your providers or anything, you'll need to wrap them in an exception handler.

So in your case it must be that the `vite` helper is being executed prior to the production vite build.

This is intended behaviour to stop you releasing assets that don't actually exist.

**Closed as completed by chrispage1** 2024-08-14 10:19 UTC
